# Generated by Django 3.2.16 on 2022-10-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_alter_foodmenu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='food_type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Mains', 'Mains'), ('Dessert', 'Dessert')], max_length=100),
        ),
    ]
