# Generated by Django 3.2.16 on 2022-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20221015_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='description',
            field=models.CharField(default='insert dish desciption', max_length=40),
        ),
    ]
