# Generated by Django 3.2.16 on 2022-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0006_auto_20221015_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='description',
            field=models.CharField(default='insert description', max_length=80),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
