# Generated by Django 3.2.16 on 2022-10-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0008_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
