# Generated by Django 3.2.16 on 2022-10-23 13:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0010_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('18:00 - 19:30', '18:00 - 19:30'), ('18:30 - 20:00', '18:30 - 20:00'), ('19:00 - 20:30', '19:00 - 20:30'), ('19:30 - 21:00', '19:30 - 21:00'), ('20:00 - 21:30', '20:00 - 21:30'), ('20:30 - 22:00', '20:30 - 22:00'), ('21:00 - 22:30', '21:00 - 22:30'), ('21:30 - 23:00', '21:30 - 23:00'), ('22:00 - 23:30', '22:00 - 23:30')], max_length=20),
        ),
    ]
