# Generated by Django 3.2.16 on 2022-10-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0011_auto_20221023_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
    ]
