# Generated by Django 3.2.16 on 2022-10-29 20:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0016_auto_20221029_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
        migrations.AddField(
            model_name='reservation',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='07', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('expired', 'expired')], default='pending', max_length=20),
        ),
    ]
