# Generated by Django 3.2.16 on 2022-10-30 15:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0017_auto_20221029_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+44', max_length=128, region=None),
        ),
    ]
